version: "3.8"

services:
  app:
    build: .
    ports:
      - "8090:8090"
    networks:
      - my-network


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER : kaushik
      POSTGRES_PASSWORD : kaushik
      POSTGRES_DB : products
    ports:
      - "5433:5432"
    networks:
      - my-network
    volumes:
      - db-data:/var/lib/postgresql/data # Persist database data

networks:
  my-network:
      driver: bridge

volumes:
  db-data :
